### ISSUE TITLE
Jenkins not connecting to AWS Secret Manager with EC2 instance profile

### ISSUE THREAD

**Issue by johnlabor** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#85]
Hi @chriskilding and anyone here that can help.

I have a Jenkins running on EC2 installed with yum, and I attach this policy to the instance:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "secretsmanager:GetSecretValue"
            ],
            "Resource": [
                "arn:aws:kms:<region>:<account>:key/<KMS key ID>",
                "arn:aws:secretsmanager:<region>:<account>:secret:*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "secretsmanager:ListSecrets",
            "Resource": "*"
        }
    ]
}
```

However, no matter what I tried Jenkins just does not able to show any keys from secret manager.

I also tried to aws configure and add the token, but Jenkins user by default does not allow login or switch from root account, and I dont want to change that behavior.

Export in env and java variable is not an option (I actually tried them later still not working).

Can someone please help I have worked on this for 6 hours and it does not work, the docs are way too simple to understand what is the exact step. The configuration UI does not even have these configurations except cache and filter, I am really in a limble now.

Thanks.

**Comment by chriskilding** [comment]
Could you try splitting your `kms:Decrypt` and `secretsmanager:GetSecretValue` policies into different statement objects?

Along the lines of:

```json
"Statement": [
        {
            "Sid": "0",
            "Effect": "Allow",
            "Action": "kms:Decrypt",
            "Resource": "arn:aws:kms:<region>:<account>:key/<KMS key ID>"
        },
        {
            "Sid": "1",
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "arn:aws:secretsmanager:<region>:<account>:secret:*"
        },
        {
            "Sid": "2",
            "Effect": "Allow",
            "Action": "secretsmanager:ListSecrets",
            "Resource": "*"
        }
]
```

 Sometimes IAM does not like policy statement objects where (1) multiple resource-scoped actions are in the same statement and (2) not all the resources are relevant to all the actions in the statement. When this happens IAM silently ignores the statement when evaluating it.

**Comment by chriskilding** [comment]
If this works for you I will paste a full JSON example into the README, where the IAM permissions are currently shown as a list. It seems quite a few people are running into this subtlety of how IAM evaluates statement objects.

**Comment by johnlabor** [comment]
Hi @chriskilding I did not group the policies up, even when I paste exactly what you provide it is still automatically group up by AWS Policy Editor. It still could not connect to Secret Manager.

It is possible to have the configurations in UI directly? Or can you write up a working step on how to get it work?
I basically tried all the methods in the authorization.md and still none of them worked. 

Thanks.

**Comment by johnlabor** [comment]
I already reboot Jenkins, reboot EC2 multiple times, and I can still only see keys in Jenkins Credential Manager, not AWS Secret Manager.

**Comment by chriskilding** [comment]
First thing to check would be the Jenkins logs. The plugin prints errors from the AWS SDK when it can't connect to AWS, so ideally get hold of those so that we can see the exact error that's happening when `ListSecrets` is called.

**Comment by chriskilding** [comment]
Although the visual policy editor has grouped the statements, I'd recommend editing it by hand to split the KMS rule from the GetSecretValue rule to see if it makes a difference. (In our company we specify our IAM policies - like all our AWS resources - in Terraform, so admittedly we don't use the visual editor ourselves and therefore don't see any bugs it might have.)

**Comment by johnlabor** [comment]
@chriskilding is there any specific policy I need to specify for the secrets inside secret manager as well?

**Comment by johnlabor** [comment]
Some logs:
```
WARNING i.j.p.c.s.AwsCredentialsProvider#getCredentials: Could not list credentials in Secrets Manager: message=[Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@sdsdsdsd: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@sdsdsdsd: The requested metadata is not found at http://IP/latest/meta-data/iam/security-credentials/]]
```

```
2021-03-03 01:34:10.190+0000 [id=20]    WARNING o.e.j.s.h.ContextHandler$Context#log: Error while serving https://IP/descriptorByName/io.jenkins.plugins.credentials.secretsmanager.config.EndpointConfiguration/testEndpointConfiguration
java.net.URISyntaxException: Expected authority at index 8: https://
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.failExpecting(URI.java:2854)
        at java.net.URI$Parser.parseHierarchical(URI.java:3102)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at com.amazonaws.util.RuntimeHttpUtils.toUri(RuntimeHttpUtils.java:195)
Caused: java.lang.IllegalArgumentException
        at com.amazonaws.util.RuntimeHttpUtils.toUri(RuntimeHttpUtils.java:197)
        at com.amazonaws.util.RuntimeHttpUtils.toUri(RuntimeHttpUtils.java:171)
        at com.amazonaws.AmazonWebServiceClient.toURI(AmazonWebServiceClient.java:329)
        at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:317)
        at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:453)
        at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at io.jenkins.plugins.credentials.secretsmanager.config.EndpointConfiguration$DescriptorImpl.doTestEndpointConfiguration(EndpointConfiguration.java:115)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
Caused: java.lang.reflect.InvocationTargetException
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
        at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
        at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
        at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
        at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
        at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1633)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
        at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:111)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:64)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
```

**Comment by chriskilding** [comment]
No, I believe the only policies you need to specify are on the Jenkins IAM principal; if it has the `secretsmanager:ListSecrets`, `secretsmanager:GetSecretValue` with an appropriate `Resource` specifier (or `*`), and optionally `kms:Decrypt` permissions then that should be sufficient.

**Comment by johnlabor** [comment]
When I tail the jenkins logs and click on the Secret Manager part in credential manager, there is no logs at all.
No errors, nothing, as if Secret Manager not even start and work.

**Comment by chriskilding** [comment]
Aha! Now we've got the logs we're cooking with gas 👍 

It looks like you're using the multi-accounts beta feature from an older version of the plugin. I removed that feature in the latest version 0.5.3 because Moto won't yet let us simulate multi-account secrets retrieval in integration tests, and anecdotally the feature failed when some ARNs were fed to it for credentials binding. I'm hesitant to officially support any feature where automated tests can't be written for it.

It's misconfigured because at least one of the clients is missing authentication info. We can try to fix that if you like, but since the feature is wobbly and not officially supported I would recommend that you turn it off instead (unless you really really need multi-account secret retrieval in the short term).

**Comment by chriskilding** [comment]
Hmm. Do you have an `~/.aws/config` or `~/.aws/credentials` file on your box? Or do you specify any AWS SDK environment variables to the Jenkins process?

**Comment by johnlabor** [comment]
@chriskilding I dont, since according to your readme, if I use instance profile I dont need to `aws configure` anymore. I do have awscli installed and that is it.

Also, the configuration in the UI I leave it empty as default, just disable the cache so I can make sure I pull every time from AWS Secret Manager.

![Screen Shot 2021-03-03 at 2 20 53 PM](https://user-images.githubusercontent.com/25555353/109860203-daba1c00-7c2b-11eb-8fda-333cadbcf6e9.png)

**Comment by johnlabor** [comment]
And since I use yum to install Jenkins, I just use systemd to start the process without changing anything in the jenkins config. I do not know if you using the jenkins.war directly? I am trying to understand how this thing didnt work, even after I tried all the `aws configure`, `env variable`, `java properties`, etc, etc.

**Comment by chriskilding** [comment]
Turning the cache off is definitely a good idea for now while we debug it. As a rule of thumb once it's working properly it's best to turn the cache on; this stores the results of `ListSecrets` for 5 minutes at a time (per Jenkins project recommendations) so that Jenkins doesn't hit AWS every time the credentials API is consulted.

**Comment by chriskilding** [comment]
Because you've got the AWS CLI on your box, would you be able to try `aws secretsmanager list-secrets` in a shell on the box (as the Jenkins user if possible) and see if that works?

**Comment by johnlabor** [comment]
I assign the role above to a IAM user, aws configure with that user token, and do the `aws secretmanager list-secrets`, everything works well.

**Comment by johnlabor** [comment]
I switch to jenkins user and did the same and works the same.

**Comment by chriskilding** [comment]
I re-read the logs and realised it's coming from `EndpointConfiguration$DescriptorImpl.doTestEndpointConfiguration`. This is a validator method which gets called when you press the 'Validate Endpoint Configuration' button in the UI. You don't seem to have a custom endpoint configuration set in your screenshot - did you have one set earlier?

**Comment by johnlabor** [comment]
@chriskilding I set it once before because I do not even know if I should set it myself or it will automatically work. But I am not using that now anymore.

**Comment by chriskilding** [comment]
Endpoint configuration is only rarely used in unusual setups, like when you want to call into an account in a different region, or when you want to use an AWS API clone like Moto. We never normally use it in typical setups.

**Comment by chriskilding** [comment]
Next thing to check is, do your Secrets Manager secrets have the right metadata attached? Do they have one of the valid `jenkins:credentials:type` tags?

**Comment by johnlabor** [comment]
> Next thing to check is, do your Secrets Manager secrets have the right metadata attached? Do they have one of the valid `jenkins:credentials:type` tags?

Can you tell me exactly what this means?
Do I need to go to my AWS account and add this to metadata of all the secrets I want to use in Jenkins?

**Comment by johnlabor** [comment]
@chriskilding OMG it works! That is the reason and why I didnt see errors. Thanks!

**Comment by peterzhuamazon** [comment]
Apart from `string` type what others types do we have?

**Comment by chriskilding** [comment]
I'll find some way to make the 'please add type tags' bit more prominent in the README. The type tag is necessary so that Jenkins can tell what kind of credential it's meant to be; without it, the secret is ignored and doesn't show as a credential in Jenkins.

**Comment by chriskilding** [comment]
I have altered the README and hopefully made this point more prominent. I also added a new troubleshooting page and linked that from the README. Could you have a look at https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/86 and tell me if that would have made it easier to understand?

**Comment by johnlabor** [comment]
Hi @chriskilding I have added some comments to the PR.
Thanks.
